version: 0.2

phases:
  install:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build
  build:
    commands:
      - docker build -t spring-api-gradle .
  post_build:
    commands:
      - echo '[{"name":"spring-api-gradle","imageUri":"529088260251.dkr.ecr.us-east-1.amazonaws.com/spring-api-gradle:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - '**/*'
  discard-paths: no
