version: 0.2

phases:
  install:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build
  build:
    commands:
      - docker build -t spring-api-gradle .

artifacts:
  files:
    - '**/*'
  base-directory: build/libs
  name: spring-api-gradle
  discard-paths: no
