version: 0.2

phases:
  install:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build
  build:
    commands:
      - docker build -t spring-api-gradle .
  post_build:
    commands:
      - echo "[{\"name\": \"spring-api-gradle\", \"imageUri\": \"spring-api-gradle:latest\"}]" > imagedefinitions.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
  discard-paths: no
