version: 0.2

phases:
  install:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build
  build:
    commands:
      - docker build -t spring-api-gradle .
  post_build:
    commands:
      - echo '[{"name":"spring-api-gradle","imageUri":"123456789012.dkr.ecr.us-east-1.amazonaws.com/spring-api-gradle:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - build/libs/gradle-0.0.1-SNAPSHOT.jar
    - imagedefinitions.json
  base-directory: build/libs
  name: spring-api-gradle
  discard-paths: no
